# Generated by Django 4.2.2 on 2023-07-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.FloatField(default=None)),
                ("amount", models.FloatField(default=0)),
                ("worth", models.FloatField(default=0)),
                ("total_profit_loss", models.FloatField(default=0)),
                ("total_profit_loss_percent", models.FloatField(default=0)),
                ("profit_loss_24h", models.FloatField(default=0)),
                ("profit_loss_percent_24h", models.FloatField(default=0)),
                ("participation_in_portfolio", models.FloatField(default=0)),
            ],
        ),
    ]
