# Generated by Django 4.2.2 on 2023-07-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_portfolio", "0002_cryptocurrency_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptocurrency",
            name="date",
            field=models.CharField(default="19/07/2023 19:34:28", max_length=25),
        ),
    ]
