# Generated by Django 4.2.2 on 2023-07-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_portfolio", "0004_alter_cryptocurrency_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrency",
            name="date",
            field=models.CharField(default="19/07/2023 19:36:41", max_length=25),
        ),
    ]
